### ISSUE TITLE
Obtain OAuth2 tokens from Guisso using client credentials

### ISSUE THREAD

**Issue by waj** [instedd/surveda-ona-connector#10]
The tokens will be used to access Surveda on behalf of the user that configured the integration.

To obtain the token without user interaction, both the connector and Surveda must be registered in Guisso as "trusted" applications. After that, in order to get a temporary Bearer token to be used during the synchronization, perform a request (using OAuth2 library) to the token endpoint (<guisso base ur>/oauth2/token) using the "client credentials" strategy and specifying the scope like: `"app=<surveda host name> user=<user's email> token_type=bearer"`.

**Comment by macoca** [comment]
Fixed with 2201bccbee4310f7dfe53a82320747c9c867e6f5
