### ISSUE TITLE
Minimal UI to select which projects/surveys to sync

### ISSUE THREAD

**Issue by waj** [instedd/surveda-ona-connector#3]
List the projects and surveys and allow selecting new surveys to be synced with ONA.

**Comment by juanboca** [comment]
Related commits:
https://github.com/instedd/surveda-ona-connector/commit/dd9e019c84141edeacb77d7b798daa2c21104123
https://github.com/instedd/surveda-ona-connector/commit/8e430f6d2a224a9c0c1275b96e59a2357053cfee
https://github.com/instedd/surveda-ona-connector/commit/aeb470b66078271cf328652da6c99be0dcd1274b
https://github.com/instedd/surveda-ona-connector/commit/b1a44bb0ecbe8419ee65135e93e46cb2a167df9d
https://github.com/instedd/surveda-ona-connector/commit/3a672445a5e8db5e2b9f4717a3c68cbc380290a2
